name = "elevator-configurator"
main = "src/worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"

[[routes]]
pattern = "vera-plot.redarch.dev"
custom_domain = true

[vars]
APP_VERSION = "v.039"

[[d1_databases]]
binding = "DB"
database_name = "elevator-configurator-db"
database_id = "907ec485-0ee5-47de-9edd-086eb82f8703"
