name = "elevator-configurator"
main = "src/worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[routes]]
pattern = "elevator-configurator.redarch.dev"
custom_domain = true
